### ISSUE TITLE
Request: Add forum to repo

### ISSUE THREAD

**Issue by JpTiger** [deanhuff/picowriter#1]
Found your project from your comment here: https://github.com/NinjaTrappeur/ultimate-writer/issues/5#issuecomment-902739646. This looks cool! Would love to comment and hear more about how it's going, but opening issue tickets like this seems like an unfair way to go about it. GitHub has a forum feature you can activate for normal comments instead.

Looking forward to hearing more about your progress!

**Comment by JpTiger** [comment]
https://docs.github.com/en/discussions/quickstart

**Comment by JpTiger** [comment]
Pfft... so if I'd, you know, _read_ your comment properly, I'd have seen [you have a subreddit](https://www.reddit.com/r/picowriter/). That'll do just fine. Thank you and good luck!

**Comment by deanhuff** [comment]
Nice...discussions is added!  I had no idea they even existed :)
